╭━━•›ꪶ ཻུ۪۪ꦽꦼ̷⸙ ━ ━ ━ ━ ꪶ ཻུ۪۪ꦽꦼ̷⸙‹•━━╮
┃╭┈─────────────⩵꙰ཱི࿐
┃╰── ⏤͟͟͞INTRO DONG──➤ ↶↷
╰━━•›ꪶ ཻུ۪۪ꦽꦼ̷⸙ ━ ━ ━ ━ ꪶ ཻུ۪۪ꦽꦼ̷⸙‹•━━͙✩̣̣̣̣
 ▬▭▬▭▬ 🚫📵🚫 ▬▭▬▭▬
╭━━•›〘 WAJIB ISI SEMUA 〙
│➳ NAMA LENGKAP :
│➳ NAMA PANGGILAN :
│➳ NAMA SAMARAN :
│➳ HOBI :
│➳ UMUR :
│➳ GENDER :
│➳ KELAS :
│➳ AGAMA :
│➳ STATUS :
│➳ CITA-CITA :
│➳ TINGGI BADAN :
│➳ BERAT BADAN :
│➳ TANGGAL LAHIR:
│➳ ALAMAT RUMAH:
│➳ KTP:
│➳ SIM:
│➳ STNK:
│➳ BPKB:
│➳ KK:
│➳ RT:
│➳ RW:
│➳ KELURAHAN:
│➳ KECAMATAN:
│➳ KABUPATEN:
│➳ KOTA:
│➳ PROVINSI:
│➳ PLANET:
│➳ GALAXY:
│➳ UNIVERSE:
│➳ LANGIT:
│➳ DARATAN:
│➳ LAUTAN:
│➳ KEPULAUAN:
│➳ SAMUDRA:
│➳ GOLONGAN DARAH :
│➳ NAMA PACAR :
│➳ JUMLAH MANTAN :
│➳ NAMA MANTAN :
│➳ NAMA BAPAK :
│➳ NAMA IBU : 
│➳ NAMA KAKAK:
│➳ KAKAK ONLINE :
│➳ KAKAK OFFLINE :
│➳ KAKAK KANDUNG :
│➳ JUMLAH KAKAK :
│➳ NAMA ADEK :
│➳ ADEK ONLINE :
│➳ ADEK OFFLINE :
│➳ ADEK KANDUNG :
│➳ JUMLAH ADEK :
│➳ NAMA KAKEK :
│➳ KAKEK DARI AYAH :
│➳ KAKEK DARI IBU :
│➳ NAMA NENEK:
│➳ NENEK DARI AYAH :
│➳ NENEK DARI IBU :
│➳ NAMA BIBI :
│➳ BIBI DARI AYAH :
│➳ BIBI DARI IBU :
│➳ NAMA PAMAN :
│➳ PAMAN DARI AYAH :
│➳ PAMAN DARI IBU :
│➳ SIFAT:
│➳ SIKAP:
│➳ ZODIAK:
│➳ WAIFU :
│➳ HUSBU :
│➳ MERK HP:
│➳ MERK MOTOR:
│➳ MERK MOBIL:
│➳ TINGKAT RUMAH:
│➳ DIAMETER RUMAH:
│➳ ALAMAT SEKOLAH:
│➳ UKURAN SEPATU:
│➳ UKURAN BAJU:
│➳ UKURAN CELANA:
│➳ INSTAGRAM:
│➳ TWITTEER:
│➳ FACEBOOK:
│➳ FILM FAVORIT:
│➳ GAME FAVORIT:
│➳ ANIME FAVORIT:
│➳ MUSIC FAVORIT:
│➳ MANGA FAVORIT:
│➳ MAKANAN FAVORIT:
│➳ MINUMAN FAVORIT:
│➳ MANHUA FAVORIT:
│➳ MANHWA FAVORIT:
│➳ SINETRON FAVORIT:
│➳ CHANNEL YOUTUBE:
│➳ UKURAN DALEMAN:
│➳ UKURAN ATASAN :
│➳ STATISTIK TUBUH:
│➳ LEBAR PINGGANG:
│➳ PANJANG TANGAN:
│➳ PANJANG KAKI:
│➳ DIAMETER KEPALA:
│➳ DIAMETER PERUT :
│➳ DIAMETER OTOT :
│➳ DIAMETER LEHER :
│➳ DIAMETER PERUT :
│➳ DIAMETER LUTUT :
│➳ DIAMETER BETIS :
│➳ PANJANG KEPALA :
│➳ LEBAR HIDUNG :
│➳ LOLI KESUKAAN :
│➳ BANYAK TEMEN :
│➳ TEMEN ONLINE :
│➳ TEMEN OFFLINE :
│➳ TEMEN MAIN VIRUS:
│➳ TEMEN MAIN GAME:
│➳ TEMEN SEKOLAH:
│➳ TEMEN RUMAH:
│➳ JENIS HEWAN PELIHARAAN:
│➳ NAMA HEWAN PELIHARAAN:
╰━ ━ ━ ━ ━ ━ ━ ━ ━ ━•⩵꙰ཱི࿐
 ▬▭▬▭▬ 🚫📵🚫 ▬▭▬▭▬

© ⏤͟͟͞BOT PRIBADI VIP